### ISSUE TITLE
GridChecker ei tööta uuendatud Columni(1.5.2) sees

### ISSUE THREAD

**Issue by sanderaido** [Oppevara/oppevara#48]
Vaade ei tööta "Kontrolli" nupu vajutamise järel.
Näide katkisest sisust: http://htk.tlu.ee/oppevara/node/2032
Töötav sisu: http://htk.tlu.ee/oppevara/node/2019

**Comment by pjotrsavitski** [comment]
The issue has nothing to do with the Column.

This is due to some of the rows of the Grid having no values within the array of selected columns. The storage seems to disregard keys with such values which produced an unexpected structure to be returned from the database.

Adding a fix to provide an empty array in these situations should be enough.

The code should be complete and committed. New patch releases should arrive soon enough.

**Comment by pjotrsavitski** [comment]
Both libraries have new versions released:
https://github.com/Oppevara/h5p-grid-checker/releases/tag/1.0.1
https://github.com/Oppevara/h5p-editor-grid-checker/releases/tag/1.0.2

Updating the GridChecker could be enough as it should also pack the latest version of Editor. Needs to be checked once new version is uploaded to the server.
